version: "3"

services:
  golang:
    tty: true
    build: ./app
    volumes:
      - ./app:/go/src/github.com/kotaroooo0/snowfall-bot/app
    ports:
      - "3000"
    command: bash -c "cd app && go get -v -d && go run main.go"
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - "golang"
