version: "3"

services:
  app:
    build: ./app
    links:
      - redis
  redis:
    image: redis:alpine
    volumes:
      - ./app/db:/data
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
