version: "3"

services:
  elasticsearch:
    build:
      context: ./elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
  app:
    build: ..
    links:
      - elasticsearch
  nginx:
    build: ./nginx
    ports:
      - "8000:8000"
    links:
      - app
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      DOMAINS: '${URL} -> http://nginx:8000'
      STAGE: "production"
      FORCE_RENEW: 'false'
    volumes:
      - /data/ssl_certs:/var/lib/https-portal
    links:
      - nginx
