version: "3"

services:
  rdb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
  redis:
    image: redis:6.0.5-alpine
    volumes:
      - ./app/db:/data
