version: "3"

services:
  rdb:
    image: mysql:5.7
    restart: always
    volumes:
      - ../mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
  redis:
    image: redis:6.0.5-alpine
    volumes:
      - ../redis:/data
    ports:
      - 6379:6379
  es:
    build:
      context: ../elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - ../elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    ports:
      - 5601:5601
    depends_on:
      - es
