version: "3"

services:
  elasticsearch:
    build:
      context: ./elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
  app:
    build: ..
    links:
      - elasticsearch
  nginx:
    build: ./nginx
    ports:
      - 80:80
    links:
      - app
