name: build

on: pull_request

jobs:
  build_no_cache_buildkit:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Create .env file
        run: echo "${{ secrets.GITHUBACTION_ENV }}" > .env

      - name: Build
        env:
          DOCKER_BUILDKIT: 1
        run: docker build .