name: build

on: pull_request

jobs:
  # ベースライン
  build_no_cache:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Create .env file
        run: echo "${{ secrets.GITHUBACTION_ENV }}" > .env

      - name: Build
        run: docker build .