name: Go

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        volumes:
          - /app/db:/data
        ports:
          - 6379:6379
        options: --entrypoint redis-server
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v2
      with:
        go-version: 1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Create .env file
      run: cd app && echo "${{ secrets.GITHUBACTION_ENV }}" > .env

    - name: Get dependencies
      run: cd app && go get -v -d

    - name: Build
      run: cd app && go build -v .

    - name: Test
      run: cd app && go test -v ./...
