name: Go

on: pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: golang:latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Create .env file
      run: echo "${{ secrets.GITHUBACTION_ENV }}" > .env

    - name: Get dependencies
      run: go get -v -d

    - name: Build
      run: go build -v .

  test:
    name: Test
    runs-on: ubuntu-latest
    container: golang:latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Create .env file
      run: echo "${{ secrets.GITHUBACTION_ENV }}" > .env

    - name: redis setup
      uses: shogo82148/actions-setup-redis@v1
      with:
        redis-version: '6.0'

    - name: Init redis data
      run: cat db/data.txt | redis-cli -n 1 --pipe

    - name: Get dependencies
      run: go get -v -d

    - name: Test
      run: REDIS_HOST=localhost go test -v ./...
