name: Go

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    container: golang:latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        volumes:
          - ./app/db:/data
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Create .env file
      run: cd app && echo "${{ secrets.GITHUBACTION_ENV }}" > .env

    - name: Init redis data
      run: sudo apt install redis-server

    - name: Get dependencies
      run: cd app && go get -v -d

    - name: Build
      run: cd app && go build -v .

    - name: Test
      run: cd app && go test -v ./...
